gde_gestion_doc_ecole:
    resource: "@GdeGestionDocEcoleBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
login:
    path:   /login
    defaults:
        _controller: GdeSecurityBundle:Security:login
        
login_check:
    path:   /login_check
    
logout:
    path:   /logout
