# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Gde\GestionDocEcoleBundle\Entity\D80Utilisateur: plaintext

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    s.bressani@bluewin.ch: { password: cuisinecuisine, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity:
                class:      Gde\GestionDocEcoleBundle\Entity\D80Utilisateur
                property:   username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#            provier:    main
        main_login:
            pattern:   ^/login$
            anonymous: true
#            provier:    main
        main:
            pattern:    ^/
            anonymous:  false
 #           provier:    main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     login
  
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }