<?php

namespace Gde\GestionDocEcoleBundle\Repository;

/**
 * D01PeriodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class D01PeriodeRepository extends \Doctrine\ORM\EntityRepository
{
}
