<?php

namespace Gde\GestionDocEcoleBundle\Repository;

/**
 * D02BrancheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class D02BrancheRepository extends \Doctrine\ORM\EntityRepository
{
}
