<?php

namespace Gde\GestionDocEcoleBundle\Repository;

/**
 * D03TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class D03TypeRepository extends \Doctrine\ORM\EntityRepository
{
}
