<?php

namespace Gde\GestionDocEcoleBundle\Repository;

/**
 * D04DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class D04DocumentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllJointureD01D02D03()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM GdeGestionDocEcoleBundle:D04Document p ORDER BY p.id ASC'
            )
            ->getResult();
    }
}
