<?php

namespace Gde\GestionDocEcoleBundle\Repository;

/**
 * D04DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class D04DocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
