<?php

namespace Gde\GestionDocEcoleBundle\Repository;

/**
 * D80UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class D80UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{

}
